src/Aspnet.Mal3ab/Controllers/CourtsController.cs
using AspnetRun.Application.Interfaces;
using AspnetRun.Shared.Dtos;
using AspnetRun.Shared.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Aspnet.Mal3ab.Controllers
{
    [Authorize]
    public class CourtsController : Controller
    {
        private readonly ICourtService _courtService;
        private readonly IWorkingHoursService _workingHoursService;
        private readonly ICourtTypeService _courtTypeService;

        public CourtsController(ICourtService courtService, IWorkingHoursService workingHoursService, ICourtTypeService courtTypeService)
        {
            _courtService = courtService;
            _workingHoursService = workingHoursService;
            _courtTypeService = courtTypeService;
        }


        // GET: CourtsController
        public async Task<ActionResult> Index()
        {
            var courts = _courtService.GetAllCourts(User.GetUserId().Value);
            return View(courts);
        }

        // GET: CourtsController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var coutDetails = await _courtService.GetCourt(id, User.GetUserId().Value);
            coutDetails.CourtType = await _courtTypeService.GetCourtTypById(id);
            return View(coutDetails);
        }

        // GET: CourtsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CourtsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CourtDto courtDto)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    var userId = User.GetUserId();
                    courtDto.UserId = userId.Value;
                    await _courtService.Add(courtDto);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    var errors = ModelState.Values.SelectMany(v => v.Errors);
                    return View(courtDto);
                }
            }
            catch (Exception e)
            {
                return View(courtDto);
            }

        }

        // GET: CourtsController/Create
        public async Task<ActionResult> AddWorkingHours(int Id)
        {
            //Id Represent The Court Id
            var court = _courtService.GetAllCourts(User.GetUserId().Value)?.FirstOrDefault(c => c.Id == Id);

            if (court is null)
            {
                return RedirectToAction(nameof(Index));
            }

            var workingHours = await _workingHoursService.GetAsync(Id);
            ViewBag.CourtId = Id;

            return View(workingHours);
        }

        // POST: CourtsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddWorkingHours(WorkinghourDto workingHourDto)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (workingHourDto.AllDays)
                    {
                        workingHourDto.FromDay = null;
                        workingHourDto.ToDay = null;
                    }
                    if (workingHourDto.AllTimes)
                    {
                        workingHourDto.FromTime = null;
                        workingHourDto.ToTime = null;
                    }
                    var result = workingHourDto.Id is null ? await _workingHoursService.AddAsync(workingHourDto, User.GetUserId().Value) : await _workingHoursService.EditAsync(workingHourDto, User.GetUserId().Value);
                    if (result is null)
                    {
                        return View();
                    }
                    return RedirectToAction(nameof(Details), result.CourtId);
                }
            }
            catch (Exception e)
            {
                return View(workingHourDto);
            }
            return View(workingHourDto);
        }



        // GET: CourtsController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CourtsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CourtsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CourtsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

src/Aspnet.Mal3ab/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewData["Title"] - Aspnet.Mal3ab</title>    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="~/img/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/css/styles.css" rel="stylesheet" />
    @await RenderSectionAsync("Styles", required: false)
</head>
<body id="page-top">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top navbar-shrink" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="#page-top"><img src="~/img/navbar-logo.svg" alt="..." /></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars ms-1"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                    <li class="nav-item"><a class="nav-link" href="#services">Services</a></li>
                    <li class="nav-item"><a class="nav-link" href="#portfolio">Portfolio</a></li>
                    <li class="nav-item"><a class="nav-link" href="#about">About</a></li>
                    <li class="nav-item"><a class="nav-link" href="#team">Team</a></li>
                    <li class="nav-item"><a class="nav-link" href="#contact">Contact</a></li>

                    @if (!User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item"><a class="nav-link nav-link-login" href="/Identity/Account/Login">Log In</a></li>
                    }
                    else
                    {
                        <li class="nav-item"><a class="nav-link nav-link-login" asp-action="Index" asp-controller="Courts">Courts</a></li>
                        <li class="nav-item"><a class="nav-link nav-link-login" href="/Identity/Account/Logout">Log Out</a></li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <!-- Masthead-->
    @RenderBody()


    <!-- Footer-->
    <footer class="footer py-4">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-4 text-lg-start">Copyright &copy; Your Website 2022</div>
                <div class="col-lg-4 my-3 my-lg-0">
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Twitter"><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Facebook"><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="LinkedIn"><i class="fab fa-linkedin-in"></i></a>
                </div>
                <div class="col-lg-4 text-lg-end">
                    <a class="link-dark text-decoration-none me-3" href="#!">Privacy Policy</a>
                    <a class="link-dark text-decoration-none" href="#!">Terms of Use</a>
                </div>
            </div>
        </div>
    </footer>

    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/js/scripts.js"></script>
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <!-- * *                               SB Forms JS                               * *-->
    <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
@*
    <!DOCTYPE html>
    <html lang="en">
    <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Aspnet.Mal3ab</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Aspnet.Mal3ab.styles.css" asp-append-version="true" />
    </head>
    <body>
    <header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Aspnet.Mal3ab</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
    <ul class="navbar-nav flex-grow-1">
    <li class="nav-item">
    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
    </li>
    <li class="nav-item">
    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </li>
    </ul>
    </div>
    </div>
    </nav>
    </header>
    <div class="container">
    <main role="main" class="pb-3">
    @RenderBody()
    </main>
    </div>

    <footer class="border-top footer text-muted">
    <div class="container">
    &copy; 2022 - Aspnet.Mal3ab - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
    </footer>

    </body>
    </html>*@